FROM jboss/keycloak:latest

ENV KEYCLOAK_USER matAdmin
ENV KEYCLOAK_PASSWORD changeit

ENV KEYCLOAK_IMPORT mat-realm.json

ENV DB_VENDOR postgres
ENV DB_ADDR mat-keyloak-bdd
ENV DB_USER keycloak
ENV DB_PASSWORD changeit

COPY config/mat-realm.json config/mat-realm.json
